### ISSUE TITLE
 UTF-8 encoded username characters are printed wrongly in the profile page

### ISSUE THREAD

**Issue by eric-glb** [PrettyGoodPing/pretty-good-complaints#1]
**Describe the bug**
 UTF-8 encoded username characters are printed wrongly in the profile page

**To Reproduce**
1. Have an Github username using UTF-8 encoding (example: Éric)
2. Go to 'https://www.prettygoodping.com/profile'
5. See the username wrongly encoded (cf. screenshot below)

**Expected behavior**
The username should be correctly printed (e.g.: Éric)

**Screenshots**
![image](https://user-images.githubusercontent.com/89578893/217488482-a246b6c4-c7aa-4c3d-b3a3-b2aed0c38f35.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 109.0

**Additional context**
Great tool! Thanks!

**Comment by oalders** [comment]
Thanks so much for your report, @eric-glb. It looks like it was an issue with the database handle. Could you let me know if it's fixed for you now?

**Comment by eric-glb** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/89578893/217789168-00ac519f-5515-47aa-9262-a4821af9c0fe.png)

Again, great tool, thanks!

**Comment by oalders** [comment]
Excellent! Looks like you got your notification email set up as well. 😄
